{{- if .Values.generateSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "generate-secret.fullname" . }}
type: Opaque
stringData:
  CRYPTO_KEY_VALUE: {{ template "generate-secret-access-key"  . }}
  CRYPTO_KEY_PROVIDER: "secret"
{{- end }}
